name: hint_field
description: "A widget to show hint or error text under the field widget."
version: 1.0.1
repository: https://github.com/RightBrainPro/hint_field
issue_tracker: https://github.com/RightBrainPro/hint_field/issues

publish_to: https://pub.rightbrain.pro/

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
