name: hint_field
description: "A widget to show hint or error text under a field."
version: 1.0.0
repository: https://github.com/darkstarx/hint_field
issue_tracker: https://github.com/darkstarx/hint_field/issues

publish_to: https://pub.rightbrain.pro/schtandart/

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
